# Generated by Django 4.1 on 2022-10-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_fathrland_customer_fatherland_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='fatherland',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Әкесінің аты'),
        ),
    ]
