# Generated by Django 4.1 on 2022-11-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_customer_fatherland'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Лауазымы'),
        ),
    ]
