# Generated by Django 4.1 on 2023-01-30 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_remove_customer_user_customer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files', verbose_name='Файл')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer', verbose_name='Қолданушы')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлдар',
                'db_table': 'employmentsfiles',
            },
        ),
    ]
