# Generated by Django 4.1 on 2023-01-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_employmentfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='file',
            field=models.FileField(default=1, upload_to='files/', verbose_name='Файл'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EmploymentFile',
        ),
    ]
