# Generated by Django 4.1 on 2023-01-31 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_employment_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employment',
            name='file',
        ),
        migrations.CreateModel(
            name='EmploymentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Файл')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer', verbose_name='Қолданушы')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлдар',
                'db_table': 'employmentsfiles',
            },
        ),
    ]
