# Generated by Django 4.1 on 2023-01-31 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_remove_employment_file_employmentfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Файл'),
        ),
        migrations.DeleteModel(
            name='EmploymentFile',
        ),
    ]
