# Generated by Django 4.1 on 2023-02-15 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_employment_file_delete_employmentfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Жұмыс орын')),
                ('bin', models.CharField(max_length=12, verbose_name='БИН')),
            ],
            options={
                'verbose_name': 'Жұмыс орын',
                'verbose_name_plural': 'Жұмыс орындар',
                'db_table': 'placeofworks',
            },
        ),
        migrations.AlterField(
            model_name='employment',
            name='command',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Құжат,күні'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='data_created',
            field=models.DateField(blank=True, null=True, verbose_name='Күні'),
        ),
        migrations.AddField(
            model_name='employee',
            name='place_of_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.placeofwork', verbose_name='Жұмыс орын'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='place_of_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.placeofwork', verbose_name='Жұмыс орын'),
        ),
    ]
